# Importação de Bibliotecas

In [6]:
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.3

In [7]:
import numpy as np
import pandas as pd
import datetime
from datetime import date, timedelta
pd.set_option('display.float_format', lambda x: '%.2f' % x)
#import matplotlib.pyplot as plt
#import seaborn as sns
#%matplotlib inline

#from tkinter import Tk
#from tkinter import filedialog

# Importação do Arquivo

In [8]:
p_cmpid   = pd.read_excel('PQ376.xlsx')      ### leitura do arquivo com os sinais dos cpmids do quadro 376
p_tpmoid  = pd.read_excel('Pt376.xlsx')      ### leitura do arquivo com os sinais dos tpmoids do quadro 376
param     = pd.read_excel('LQ376.xlsx')      ### leitura do arquivo com o layout atualizado do quadro 376

In [9]:
df = pd.read_csv('376_Trabalho.csv')
df = df.drop(columns=['Unnamed: 0'])
df['DTMRFMESANO'] = df['DTMRFMESANO'].astype('datetime64')
df

,ESRSEQ,ENTCODIGO,MRFMESANO,QUAID,TPMOID,CMPID,RAMCODIGO,ESRDATAINICIO,ESRDATAFIM,ESRDATAOCORR,...,DTESRDATAFIM,DTESRDATAOCORR,DTESRDATAREG,DTESRDATACOMUNICA,fESRVALORMOV,fESRVALORMON,Empresa,Desc_ramo,Criador,Data do output
0,1,2798,20200131,376,2,1001,622,20191130,20201130,20200106,...,2020-11-30 00:00:00.000000,2020-01-06 00:00:00.000000,2020-01-07 00:00:00.000000,2020-01-06 00:00:00.000000,-7071.08,0.00,ARGO SEGUROS BRASIL S.A.,22 - TRANSPORTE INTERNACIONAL,Haylton,2020-10-20 12:39:58.152872
1,3,2798,20200131,376,4,1001,622,20150401,20150430,20150425,...,2015-04-30 00:00:00.000000,2015-04-25 00:00:00.000000,2015-06-01 00:00:00.000000,2015-05-20 00:00:00.000000,-5721.54,0.00,ARGO SEGUROS BRASIL S.A.,22 - TRANSPORTE INTERNACIONAL,Haylton,2020-10-20 12:39:58.152872
2,14,2798,20200131,376,2,1012,622,20190504,20200504,20191223,...,2020-05-04 00:00:00.000000,2019-12-23 00:00:00.000000,2020-01-06 00:00:00.000000,2020-01-03 00:00:00.000000,3312.71,217.18,ARGO SEGUROS BRASIL S.A.,22 - TRANSPORTE INTERNACIONAL,Haylton,2020-10-20 12:39:58.152872
3,15,2798,20200131,376,2,1012,622,20190504,20200504,20190912,...,2020-05-04 00:00:00.000000,2019-09-12 00:00:00.000000,2019-09-17 00:00:00.000000,2019-09-12 00:00:00.000000,7274.89,646.33,ARGO SEGUROS BRASIL S.A.,22 - TRANSPORTE INTERNACIONAL,Haylton,2020-10-20 12:39:58.152872
4,17,2798,20200131,376,2,1001,622,20191019,20201019,20200116,...,2020-10-19 00:00:00.000000,2020-01-16 00:00:00.000000,2020-01-24 00:00:00.000000,2020-01-23 00:00:00.000000,2091.89,491.83,ARGO SEGUROS BRASIL S.A.,22 - TRANSPORTE INTERNACIONAL,Haylton,2020-10-20 12:39:58.152872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170696,1429,2798,20190930,376,2,1001,632,20180814,20190814,20190328,...,2019-08-14 00:00:00.000000,2019-03-28 00:00:00.000000,2019-04-01 00:00:00.000000,2019-03-28 00:00:00.000000,-65659.40,-4009.37,ARGO SEGUROS BRASIL S.A.,32 - R.C.Trans.Carga Viag.Int.-RCTR-VI-C,Haylton,2020-10-20 12:39:58.152872
170697,3591,2798,20190930,376,2,1001,632,20180814,20190814,20190810,...,2019-08-14 00:00:00.000000,2019-08-10 00:00:00.000000,2019-08-14 00:00:00.000000,2019-08-10 00:00:00.000000,0.00,-3308.88,ARGO SEGUROS BRASIL S.A.,32 - R.C.Trans.Carga Viag.Int.-RCTR-VI-C,Haylton,2020-10-20 12:39:58.152872
170698,1731,2798,20191031,376,2,1001,632,20180814,20190814,20190328,...,2019-08-14 00:00:00.000000,2019-03-28 00:00:00.000000,2019-04-01 00:00:00.000000,2019-03-28 00:00:00.000000,0.00,-450.56,ARGO SEGUROS BRASIL S.A.,32 - R.C.Trans.Carga Viag.Int.-RCTR-VI-C,Haylton,2020-10-20 12:39:58.152872
170699,1268,2798,20191130,376,4,1001,632,20180814,20190814,20190328,...,2019-08-14 00:00:00.000000,2019-03-28 00:00:00.000000,2019-04-01 00:00:00.000000,2019-03-28 00:00:00.000000,13415.53,0.00,ARGO SEGUROS BRASIL S.A.,32 - R.C.Trans.Carga Viag.Int.-RCTR-VI-C,Haylton,2020-10-20 12:39:58.152872
170700,2276,2798,20191130,376,2,1001,632,20180814,20190814,20190328,...,2019-08-14 00:00:00.000000,2019-03-28 00:00:00.000000,2019-04-01 00:00:00.000000,2019-03-28 00:00:00.000000,-111.37,603.08,ARGO SEGUROS BRASIL S.A.,32 - R.C.Trans.Carga Viag.Int.-RCTR-VI-C,Haylton,2020-10-20 12:39:58.152872

# Tratativa dos dados QE

In [10]:
data = []
valor = []
desc_cmpid = []
cmpid = []
ramc = []

dadosano = set(df['MESano'])  # Verificando os anos que estao sendo usados
dadosramcod = set(df['RAMCODIGO'])  # Verificando os RAMCOD que estao sendo usados

In [11]:
###########################################
##Criando Função Para criação dos valores##
###########################################


def valdata(date,ram):


    # Selecionando os TPMOIDs com CMPID 1001
                                                                    # Criando mascara para filtrar colunas de meu interesse
    mask_cmpid_1001 = (df['CMPID']==1001) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1001]['fESRVALORMOV']),2))
    cmpid.append(12184)
    desc_cmpid.append('Direto - Administrativo')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1002

    mask_cmpid_1002 = (df['CMPID']==1002) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1002]['fESRVALORMOV']),2))
    cmpid.append(12185)
    desc_cmpid.append('Cosseguro Aceito – Administrativo')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1003

    mask_cmpid_1003 = (df['CMPID']==1003) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1003]['fESRVALORMOV']),2))    
    cmpid.append(12186)
    desc_cmpid.append('Cosseguro Cedido – Administrativo') # Criando descrição
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1004

    mask_cmpid_1004 = (df['CMPID']==1004) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1004]['fESRVALORMOV']),2))
    cmpid.append(12208)
    desc_cmpid.append('Salvados e Ressarcidos – Administrativo')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1005

    mask_cmpid_1005 = (df['CMPID']==1005) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1005]['fESRVALORMOV']),2))
    cmpid.append(12224)
    desc_cmpid.append('Salvados e Ressarcidos ao Ressegurador - Administrativo')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1006

    mask_cmpid_1006 = (df['CMPID']==1006) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1006]['fESRVALORMOV']),2))
    cmpid.append(12188)
    desc_cmpid.append('Direto - Judicial')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1007

    mask_cmpid_1007 = (df['CMPID']==1007) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1007]['fESRVALORMOV']),2))
    cmpid.append(12189)
    desc_cmpid.append('Cosseguro Aceito – Judicial')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1008

    mask_cmpid_1008 = (df['CMPID']==1008) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1008]['fESRVALORMOV']),2))
    cmpid.append(12190)
    desc_cmpid.append('Cosseguro Cedido – Judicial')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1009

    mask_cmpid_1009 = (df['CMPID']==1009) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1009]['fESRVALORMOV']),2))
    cmpid.append(12209)
    desc_cmpid.append('Salvados e Ressarcidos – Judicial')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1010

    mask_cmpid_1010 = (df['CMPID']==1010) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)

    data.append(date)
    valor.append(round(sum(df.loc[mask_cmpid_1010]['fESRVALORMOV']),2))
    cmpid.append(12225)
    desc_cmpid.append('Salvados e Ressarcidos ao Ressegurador - Judicial')
    ramc.append(ram)


    # Selecionando os TPMOIDs com CMPID 1011

    mask_cmpid_1011 = (df['CMPID']==1011) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)
    df_cmpid_1011 = df.loc[mask_cmpid_1011]

    campo_cmpid_1011 = round(sum(df_cmpid_1011['fESRVALORMOV']),2)


    # Selecionando os TPMOIDs com CMPID 1012
 
    mask_cmpid_1012 = (df['CMPID']==1012) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)
    df_cmpid_1012 = df.loc[mask_cmpid_1012]

    campo_cmpid_1012 = round(sum(df_cmpid_1012['fESRVALORMOV']),2)


    # Selecionando os TPMOIDs com CMPID 1013

    mask_cmpid_1013 = (df['CMPID']==1013) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)
    df_cmpid_1013 = df.loc[mask_cmpid_1013]
    
    campo_cmpid_1013 = round(sum(df_cmpid_1013['fESRVALORMOV']),2)


    # Selecionando os TPMOIDs com CMPID 1014

    mask_cmpid_1014 = (df['CMPID']==1014) & ((df['TPMOID']==1)|(df['TPMOID']==2)|(df['TPMOID']==5)|(df['TPMOID']==6)) & (df['MESano'] == date) & (df['RAMCODIGO'] == ram)
    df_cmpid_1014 = df.loc[mask_cmpid_1014]
    
    campo_cmpid_1014 = round(sum(df_cmpid_1014['fESRVALORMOV']),2)


    # Criando campos com mais de um CMPID
    # Campo Recuperação de Sinistros não Pagos + já Pagos – Administrativo
    campo_cmpid_1011_1012 = round((sum(df_cmpid_1011['fESRVALORMOV'])) + (sum(df_cmpid_1012['fESRVALORMOV'])),2)

    data.append(date)
    valor.append(campo_cmpid_1011_1012)
    cmpid.append(12218)
    desc_cmpid.append('Recuperação de Sinistros não Pagos + já Pagos – Administrativo')
    ramc.append(ram)

    # Campo Recuperação de Sinistros não Pagos + já Pagos – Judial
    campo_cmpid_1013_1014 = round((sum(df_cmpid_1013['fESRVALORMOV'])) + (sum(df_cmpid_1014['fESRVALORMOV'])),2)

    data.append(date)
    valor.append(campo_cmpid_1013_1014)
    cmpid.append(12219)
    desc_cmpid.append('Recuperação de Sinistros não Pagos + já Pagos - Judicial')
    ramc.append(ram)

    # Campo cmpid_1001_2_3_6_7_8
    campo_cmpid_1001_2_3_6_7_8 = (round(sum(df.loc[mask_cmpid_1001]['fESRVALORMOV']),2)) + (round(sum(df.loc[mask_cmpid_1002]['fESRVALORMOV']),2)) - (round(sum(df.loc[mask_cmpid_1003]['fESRVALORMOV']),2)) + (round(sum(df.loc[mask_cmpid_1006]['fESRVALORMOV']),2)) + (round(sum(df.loc[mask_cmpid_1007]['fESRVALORMOV']),2)) - (round(sum(df.loc[mask_cmpid_1008]['fESRVALORMOV']),2))
    data.append(date)
    valor.append(campo_cmpid_1001_2_3_6_7_8)
    cmpid.append(12234)
    desc_cmpid.append('Despesas Financeiras - PSL')
    ramc.append(ram)

    # Campo cmpid_1011_12_13_14
    campo_cmpid_1011_12_13_14 = (campo_cmpid_1011) + (campo_cmpid_1012) + (campo_cmpid_1013) + (campo_cmpid_1014)
    data.append(date)
    valor.append(campo_cmpid_1011_12_13_14)
    cmpid.append(12235)
    desc_cmpid.append('Recuperação das Despesas Financeiras - PSL')
    ramc.append(ram)

    # Finalizando
    print('Para Data {} e Ramo {} campos analisados e dados coletados.\n'.format(date,ram))  # Gernado Print informativo

In [12]:
# Loop For para percorrer os 12 meses na função Valores_Data
lista_for = []
for dates in dadosano:
    for ram in dadosramcod:
        verifica = valdata(dates,ram)
pdd = {'DTmrfMesAno':data,"vdrValor":valor,'CMPID':cmpid,'Desc_CMPID':desc_cmpid,'ramo_s1':ramc}

Para Data 2018-11-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-11-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-11-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-04-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-09-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-10-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-06-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-09-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-02-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-08-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-07-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-07-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-05-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2020-01-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-05-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-12-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-09-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-03-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-10-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-04-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-08-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-09-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-08-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-07-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-01-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2020-07-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-12-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2020-04-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-07-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-03-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-11-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-12-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-01-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-08-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-04-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2020-03-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-03-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2020-08-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-10-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-03-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-02-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-06-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-03-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-05-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-07-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2020-06-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-06-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2020-05-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-02-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2020-02-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-06-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-02-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-04-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-11-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-08-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2015-10-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-10-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-12-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-05-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-12-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2019-09-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-01-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-11-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-01-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2018-06-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-04-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2016-05-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 196 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 167 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 776 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 775 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 171 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 652 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 621 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 654 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 622 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 655 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 656 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 141 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 310 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 118 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 632 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 313 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 378 campos analisados e dados coletados.

Para Data 2017-01-01 00:00:00.000000 e Ramo 351 campos analisados e dados coletados.

In [13]:
df_geral_qe = pd.DataFrame(pdd)  # Gerando Data Frame Transposta
df_geral_qe = df_geral_qe.sort_values('DTmrfMesAno',ignore_index=True)
df_geral_qe['DTmrfMesAno'] = df_geral_qe['DTmrfMesAno'].astype('datetime64')
df_geral_qe.loc[:,'entCodigo'] = set(df['ENTCODIGO'])
df_geral_qe

,DTmrfMesAno,vdrValor,CMPID,Desc_CMPID,ramo_s1,entCodigo
0,2015-01-01,1177270.21,12234,Despesas Financeiras - PSL,351,2798
1,2015-01-01,0.00,12188,Direto - Judicial,621,2798
2,2015-01-01,33.34,12224,Salvados e Ressarcidos ao Ressegurador - Admin...,621,2798
3,2015-01-01,196018.31,12208,Salvados e Ressarcidos – Administrativo,621,2798
4,2015-01-01,0.00,12186,Cosseguro Cedido – Administrativo,621,2798
...,...,...,...,...,...,...
16879,2020-08-01,0.00,12190,Cosseguro Cedido – Judicial,141,2798
16880,2020-08-01,0.00,12189,Cosseguro Aceito – Judicial,141,2798
16881,2020-08-01,0.00,12188,Direto - Judicial,141,2798
16882,2020-08-01,0.00,12224,Salvados e Ressarcidos ao Ressegurador - Admin...,310,2798
16883,2020-08-01,0.00,12184,Direto - Administrativo,196,2798

In [14]:
#df_valores.to_excel('Valores_Campos_376.xlsx')   # Exportando DataFrame final para Excel

# Puxando Base de Dados FIP (em CSV)

In [15]:
df_comparacao = pd.read_csv('ValoresMovRamos.csv',sep=';')  # Lendo o Arquivo CSV

In [16]:
# Passando entCodigo para int e vdrValor para float e mrfMesAno para date 
df_comparacao['entCodigo'] = df_comparacao['entCodigo'].astype('int64') # Valor int entCodigo

df_comparacao['vdrValor'] = df_comparacao['vdrValor'].apply(lambda x : x.replace(",", '.')) 
df_comparacao['vdrValor'] = df_comparacao['vdrValor'].astype('float64')  # Valor float vdrValor
df_comparacao['vdrValor'] = df_comparacao['vdrValor'].apply(lambda x : round(x,2))  # Arredondando vdrValor com duas casas decimais

df_comparacao['CMPID'] = df_comparacao['CMPID'].astype('int64') # Valor int CMPID

df_comparacao['ramo_s1'] = (df_comparacao['graCodigo'].astype(str) + df_comparacao['ramCodigo'].astype(str))
df_comparacao['ramo_s1'] = df_comparacao['ramo_s1'].astype('int64')

import datetime
list_date = []   #Criando lista
for i in df_comparacao['mrfMesAno']:
    format_str = '%d/%m/%Y 00:00:00'
    datetime_obj = datetime.datetime.strptime(i, format_str).date()   # Transformando cada item para Datetime
    list_date.append(datetime_obj)      # Adicionando a lista
df_comparacao.loc[:,'DTmrfMesAno'] = list_date    # Alocando a lista no DataFrame
df_comparacao['DTmrfMesAno'] = df_comparacao['DTmrfMesAno'].astype('datetime64')
df_comparacao = df_comparacao.dropna(axis=1) # Eliminando colunas com valores Nulos
df_comparacao.head()  # Visualisando DataFrame gerado

,entCodigo,mrfMesAno,ramCodigo,CMPID,vdrValor,graCodigo,ramo_s1,DTmrfMesAno
0,2798,1/12/2011 00:00:00,10,9,0.00,3,310,2011-12-01
1,2798,1/12/2011 00:00:00,10,10,0.00,3,310,2011-12-01
2,2798,1/12/2011 00:00:00,10,20,0.00,3,310,2011-12-01
3,2798,1/12/2011 00:00:00,10,408,0.00,3,310,2011-12-01
4,2798,1/12/2011 00:00:00,10,978,0.00,3,310,2011-12-01

# Comparando valores do QE com FIP

In [17]:
df_merge = pd.merge(df_geral_qe, df_comparacao, on=['entCodigo','CMPID','DTmrfMesAno','ramo_s1'], how='inner',suffixes=('_qe', '_fip'))
df_merge = df_merge.drop(['mrfMesAno','ramCodigo','graCodigo'],axis=1)

In [18]:
#########################
#Arquivo Modelo Empresas#
#########################

arq_codsusep = pd.read_excel('Quadro376.xlsx','Cod_SUSEP',fileEncoding = "UTF-8",encoding = 'latin_1', dtype=str) # Lendo arquivo parametro
ent = []                                          # Criando lista vazia
for i in arq_codsusep['Cod_SUSEP'].astype('int64'):
    ent.append(i)                                # Adicionando Todas as EntidadeCod em uma lista
desc = []                                        # Criando lista vazia
for i in arq_codsusep['Empresa']:
    desc.append(i)                                # Adicionando Todos os Nomes de Empresa em uma lista
    
mod = dict(zip(ent, desc))                        # Crando dicionario
#Transformalo em Data Frame
df_mod_e = pd.DataFrame(columns=['entCodigo','Empresa'])
df_mod_e.loc[:,'entCodigo'] = mod.keys()
df_mod_e.loc[:,'Empresa'] = mod.values()

##########################
#Arquivo Modelo RAMCODIGO#
##########################

arq_ramcod = pd.read_excel('Quadro376.xlsx','RAMCODIGO',fileEncoding = "UTF-8",encoding = 'latin_1', dtype=str) # Lendo arquivo parametro
ent = []                                          # Criando lista vazia
for i in arq_ramcod['ramo_s1'].astype('int64'):
    ent.append(i)                                # Adicionando Todas as EntidadeCod em uma lista
desc = []                                        # Criando lista vazia
for i in arq_ramcod['ramNome']:
    desc.append(i)                                # Adicionando Todos os Nomes de Empresa em uma lista
    
mod = dict(zip(ent, desc))                        # Crando dicionario
#Transformalo em Data Frame
df_mod_r = pd.DataFrame(columns=['ramo_s1','Desc_ramo'])
df_mod_r.loc[:,'ramo_s1'] = mod.keys()
df_mod_r.loc[:,'Desc_ramo'] = mod.values()

In [19]:
# Juntando empresa com descrição a partir do arquivo modelo
df_merge = pd.merge(df_merge,df_mod_e,on='entCodigo',how='inner')
df_merge = pd.merge(df_merge,df_mod_r,on='ramo_s1',how='inner')
df_merge = df_merge[['DTmrfMesAno','vdrValor_qe','vdrValor_fip','CMPID','Desc_CMPID','entCodigo','Empresa','ramo_s1','Desc_ramo']]
df_merge

,DTmrfMesAno,vdrValor_qe,vdrValor_fip,CMPID,Desc_CMPID,entCodigo,Empresa,ramo_s1,Desc_ramo
0,2015-01-01,1177270.21,1795.76,12234,Despesas Financeiras - PSL,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
1,2015-01-01,68782.00,0.00,12235,Recuperação das Despesas Financeiras - PSL,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
2,2015-01-01,0.00,0.00,12219,Recuperação de Sinistros não Pagos + já Pagos ...,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
3,2015-01-01,0.00,0.00,12225,Salvados e Ressarcidos ao Ressegurador - Judicial,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
4,2015-01-01,0.00,0.00,12209,Salvados e Ressarcidos – Judicial,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
...,...,...,...,...,...,...,...,...,...
16851,2020-08-01,0.00,0.00,12208,Salvados e Ressarcidos – Administrativo,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O
16852,2020-08-01,10285.00,-6171.00,12186,Cosseguro Cedido – Administrativo,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O
16853,2020-08-01,163796.56,152188.98,12185,Cosseguro Aceito – Administrativo,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O
16854,2020-08-01,92184.00,-83956.00,12184,Direto - Administrativo,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O
16855,2020-08-01,0.00,0.00,12224,Salvados e Ressarcidos ao Ressegurador - Admin...,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O

In [22]:
mask_erro = (df_merge['vdrValor_qe'].astype('int64') != df_merge['vdrValor_fip'].astype('int64') )
df_erros = df_merge.loc[mask_erro]
df_erros

,DTmrfMesAno,vdrValor_qe,vdrValor_fip,CMPID,Desc_CMPID,entCodigo,Empresa,ramo_s1,Desc_ramo
0,2015-01-01,1177270.21,1795.76,12234,Despesas Financeiras - PSL,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
1,2015-01-01,68782.00,0.00,12235,Recuperação das Despesas Financeiras - PSL,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
9,2015-01-01,0.00,-934.21,12208,Salvados e Ressarcidos – Administrativo,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
12,2015-01-01,1177270.21,395270.21,12184,Direto - Administrativo,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
15,2015-02-01,2427268.72,1823.52,12234,Despesas Financeiras - PSL,2798,ARGO SEGUROS BRASIL S.A.,351,51 - R. C. Geral
...,...,...,...,...,...,...,...,...,...
16843,2020-08-01,245695.56,112707.29,12234,Despesas Financeiras - PSL,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O
16845,2020-08-01,166099.79,64000.09,12218,Recuperação de Sinistros não Pagos + já Pagos ...,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O
16852,2020-08-01,10285.00,-6171.00,12186,Cosseguro Cedido – Administrativo,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O
16853,2020-08-01,163796.56,152188.98,12185,Cosseguro Aceito – Administrativo,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O
16854,2020-08-01,92184.00,-83956.00,12184,Direto - Administrativo,2798,ARGO SEGUROS BRASIL S.A.,310,10 - R.C.Administradores e Diretores-D&O

In [23]:
# Adicionando Colunas Extras nos DataFrames
from datetime import datetime
data_presente = datetime.now()    # Obtendo data presente
nome = input("Insira seu nome: ") # Obtendo nome
df_merge.loc[:,'Criador'] = nome ### insere a coluna com o nome do criador da tabela
df_merge.loc[:,'Data do output'] = data_presente ### insere a coluna com a data de criacao da tabela
if len(df_erros) > 0:
    df_erros.loc[:,'Criador'] = nome ### insere a coluna com o nome do criador da tabela
    df_erros.loc[:,'Data do output'] = data_presente ### insere a coluna com a data de criacao da tabela

Insira seu nome: Haylton

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [24]:
df_erros.to_csv('376_Erros_Correspondencia.csv')

In [25]:
df_merge.to_csv('376_Correspondencia.csv')

# Testes

In [ ]:
df_erros_copy = df_erros.copy()  # Copiando DF Erro
#df_erros_copy['ramCod'] = pd.DataFrame(df_comparacao.groupby('DTmrfMesAno')['ramCodigo'])
df_erros_copy = pd.merge(df_erros_copy,df_comparacao[['DTmrfMesAno','ramo_s1']],on='DTmrfMesAno')  # Trazendo coluna ramo_s1
df_erros_copy = df_erros_copy.drop_duplicates()     # Eliminando linhas duplicadas

arq_ramcod = pd.read_excel('Quadro376.xlsx','RAMCODIGO',fileEncoding = "UTF-8",encoding = 'latin_1', dtype=str) # Lendo arquivo parametro
ram = []                                          # Criando lista vazia
for i in arq_ramcod['ramo_s1'].astype('int64'):
    ram.append(i)                                # Adicionando Todos os Ramos em uma lista
desc = []                                         # Criando lista vazia
for i in arq_ramcod['ramNome']:
    desc.append(i)                                # Adicionando Todos as Descrições Ramos em uma lista
    
mod = dict(zip(ram, desc))                        # Tranformando as listas em dicionario modelo

df_erros_copy['desc_ramo_s1'] = df_erros_copy['ramo_s1'].copy()
def quality(item):                               # Criando funcao de alteracao de valores para nomes
    if item == mod.keys():
        return mod.values()
    else:
        return mod.values()
df_erros_copy['desc_ramo_s1'] = df_erros_copy['desc_ramo_s1'].apply(lambda x: quality(x))   # Aplicando função

arq_codsusep = pd.read_excel('Quadro376.xlsx','Cod_SUSEP',fileEncoding = "UTF-8",encoding = 'latin_1', dtype=str) # Lendo arquivo parametro
ent = []                                          # Criando lista vazia
for i in arq_codsusep['Cod_SUSEP'].astype('int64'):
    ent.append(i)                                # Adicionando Todas as EntidadeCod em uma lista
desc = []                                        # Criando lista vazia
for i in arq_codsusep['Empresa']:
    desc.append(i)                                # Adicionando Todos os Nomes de Empresa em uma lista
    
mod = dict(zip(ent, desc))                        # Tranformando as listas em dicionario modelo

df_erros_copy['Empresa'] = df_erros_copy['entCodigo'].copy()
def quality(item):                               # Criando funcao de alteracao de valores para nomes
    if item == mod.keys():
        return mod.values()
    else:
        pass
df_erros_copy['Empresa'] = df_erros_copy['Empresa'].apply(lambda x: quality(x))   # Aplicando função
df_erros_copy = df_erros_copy[['CMPID','DTmrfMesAno','vdrValor_qe','vdrValor_fip','entCodigo','Empresa','ramo_s1','desc_ramo_s1']]
                                                                                    # Definindo ordem das colunas
df_erros_copy

In [ ]:
df_erros_copy['Empresa'] = df_erros_copy['entCodigo'].copy()

def quality(item):                               # Criando funcao de alteracao de valores para nomes
    if item in df_mod['e'].values():
        return df_mod.loc['E']
    else:
        pass
df_erros_copy['Empresa'] = df_erros_copy['Empresa'].apply(lambda item: quality(item))   # Aplicando função
df_erros_copy

In [ ]:
for i in df_mod['e']:
    if i == 2798:
        print(df_mod.iloc['E'])
    else:
        print('no')

In [ ]:
df_erros_copy['Empresa'] = df_erros_copy['entCodigo'].copy()

def quality(item):                               # Criando funcao de alteracao de valores para nomes
    if item not in df_mod['e']:
        return df_mod.loc['E']
    else:
        print(item)
df_erros_copy['Empresa'] = df_erros_copy['Empresa'].apply(lambda item: quality(item))   # Aplicando função
df_erros_copy

In [ ]:
df_erros_copy['Empresa'] = df_erros_copy['entCodigo'].copy()
df_erros_copy['Empresa']

In [ ]:
df_erros_copy = df_erros.copy()  # Copiando DF Erro
df_erros_copy = df_erros_copy.drop_duplicates()


arq_codsusep = pd.read_excel('Quadro376.xlsx','Cod_SUSEP',fileEncoding = "UTF-8",encoding = 'latin_1', dtype=str) # Lendo arquivo parametro
ent = []                                          # Criando lista vazia
for i in arq_codsusep['Cod_SUSEP'].astype('int64'):
    ent.append(i)                                # Adicionando Todas as EntidadeCod em uma lista
desc = []                                        # Criando lista vazia
for i in arq_codsusep['Empresa']:
    desc.append(i)                                # Adicionando Todos os Nomes de Empresa em uma lista
    
mod = dict(zip(ent, desc))

df_erros_copy['Empresa'] = df_erros_copy['entCodigo'].copy()

def quality(item):                               # Criando funcao de alteracao de valores para nomes
    if item in mod.keys():
        item.replace(mod.keys(),mod.values())
    else:
        pass
df_erros_copy['Empresa'] = df_erros_copy['Empresa'].apply(lambda x: quality(x))   # Aplicando função
df_erros_copy

In [ ]:
mod#.values()

In [ ]:
# Adicionando Colunas Extras nos DataFrames
from datetime import datetime
data_presente = datetime.now()    # Obtendo data presente
nome = input("Insira seu nome: ") # Obtendo nome
df_merge.loc[:,'Criador'] = nome ### insere a coluna com o nome do criador da tabela
df_merge.loc[:,'Data do output'] = data_presente ### insere a coluna com a data de criacao da tabela
df_erros_copy.loc[:,'Criador'] = nome ### insere a coluna com o nome do criador da tabela
df_erros_copy.loc[:,'Data do output'] = data_presente ### insere a coluna com a data de criacao da tabela

In [ ]:
df_erros_copy.to_csv('376_Erros_Correspondencia.csv')

In [ ]:
df_merge.to_csv('376_Correspondencia.csv')

# Conectando com o Access

In [ ]:
# Biblioteca:
#import pyodbc